version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gobi
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  gobi:
    build: .
    depends_on:
      - db
    environment:
      GOBI_ENV: dev
      DATA_SOURCE_SECRET: 12345678901234567890123456789012
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  db_data: 