default:
  server:
    port: "8080"
  jwt:
    secret: "default_jwt_secret"
  database:
    type: "sqlite"
    dsn: "gobi.db"

dev:
  server:
    port: "8080"
  jwt:
    secret: "dev_jwt_secret"
  database:
    type: "mysql"
    dsn: "user:password@tcp(127.0.0.1:3306)/gobi?charset=utf8mb4&parseTime=True&loc=Local"

prod:
  server:
    port: "8080"
  jwt:
    secret: "prod_jwt_secret"
  database:
    type: "postgres"
    dsn: "host=localhost user=postgres password=pass dbname=gobi port=5432 sslmode=disable" 